#!/bin/sh
#Create the mesh for the simulation
./Allclean
echo "Started simulation"

blockMesh >> log &

#Run the solver and save data-log
simpleFoam >> log &
sleep 5   

#Read vals from sample
simpleFoam -postProcess -latestTime
#simpleFoam -postProcess -func sample -latestTime >> sampleLog
echo "Finished simulation at:"
echo "pwd: $(pwd)"
